### ISSUE TITLE
support for 2FA (2 Factor Authentication)

### ISSUE THREAD

**Issue by consultantleon** [openconnect/openconnect-gui#231]
through the UI I cannot sign into my company network as they implemented 2 factor authentication.
Instead of just 1 password, 2 passwords are requested and we have a special key tool to generate a unique number as the 2nd password.

With openconnect.exe console I do manage to login fine so it'd be nice if the UI supports a 2nd password entry field. The first password is the company domain password and relatively stable (would be nice to save) the 2nd password is different on each connect attempt (changes timebound)

The console shows the Password: prompt twice, it should be rather simple to interact with that for 2FA I'd guess:

```
 Please enter your username and password.
 Username: myuserid
Password:
 Password:
```
